# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 63676b245a095a23e97e9a70a54cad6c9cad00ca3364b564823b0e8a2734da34581d54e8161bf04df24e7b3c68039d8bf98be8c8e027e3a41da97ab1d9480dae

test:
  secret_key_base: e40ff521657e649068118bb361a56e95b09e09086cca1eaf4d8b3b6c1be2b3a5aac3af13a3f6cf0a5683f23006d3a28934ec16689898223d9eb97c939381bb73

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
